import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Boxes, CheckCircle2, Factory, Globe2, GraduationCap, Layers3, PackageCheck, Palette, School, ShieldCheck, ShoppingBag, Sparkles, Store, Tags, Truck, Users } from "lucide-react";
import { Newsletter } from "@/components/forms/newsletter";
import { ProductCard } from "@/components/products/product-card";
import { JsonLd } from "@/components/seo/json-ld";
import { categoryLabels, products } from "@/data/products";
import type { ProductCategory } from "@/types/commerce";

const categories: { category: ProductCategory; copy: string; image: string; href: string }[] = [
  { category: "match", copy: "Touch and flight focused options for organized play.", image: "/images/category-match-balls.svg", href: "/match-balls/" },
  { category: "training", copy: "Durable specifications for repeated sessions.", image: "/images/category-training-balls.svg", href: "/training-balls/" },
  { category: "futsal", copy: "Controlled-rebound concepts for indoor courts.", image: "/images/category-futsal-balls.svg", href: "/futsal-balls/" },
  { category: "kids", copy: "Approachable sizes for developing young players.", image: "/images/category-kids-footballs.svg", href: "/kids-footballs/" },
  { category: "custom", copy: "Your crest, palette, packaging and private label.", image: "/images/category-custom-footballs.svg", href: "/custom-footballs/" },
];
const faqs = [
  ["Where are the footballs manufactured?", "Products are developed and manufactured in Sialkot, Pakistan. Exact specifications and production arrangements are confirmed for each order."],
  ["Do you ship worldwide?", "International shipping can be arranged. Cost and transit estimates depend on quantity, packing, service and destination."],
  ["Can I add my club logo?", "Yes. Logo printing, colors, packaging and construction can be discussed. Minimum quantities and artwork requirements must be confirmed."],
  ["Are the products certified?", "Certification information is available on request. No certification should be assumed unless it is documented for the specific product and order."],
];

export default function HomePage() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">From the football-making city</span><h1>Built in Sialkot.<br /><em>Ready for your game.</em></h1><p>Premium factory-direct footballs for players, clubs, academies, retailers and brands—developed to a clear specification and delivered worldwide.</p><div className="hero-actions"><Link href="/shop/" className="button gold">Shop footballs <ArrowRight /></Link><Link href="/wholesale/" className="button hero-secondary">Request wholesale quote</Link></div><div className="hero-note"><CheckCircle2 /> Honest demonstration catalogue. Final product details are confirmed before ordering.</div></div><div className="hero-visual"><div className="hero-orbit"><span>Design</span><span>Develop</span><span>Deliver</span></div><Image src="/images/hero-football.svg" alt="Stylized football representing factory-direct football manufacturing" width={760} height={760} priority /><div className="origin-card"><Factory /><span>Manufactured in<strong>Sialkot, Pakistan</strong></span></div></div></div></section>
    <section className="trust-strip" aria-label="Service highlights"><div className="container trust-grid">{[[Factory, "Factory direct", "A shorter path from specification to supply"], [ShieldCheck, "Quality checked", "Defined checks for finish, shape and air retention"], [Globe2, "Worldwide shipping", "Quoted for the order and destination"], [Palette, "Custom branding", "Logo, color and packaging options"], [PackageCheck, "Secure external payment", "Hosted options only when configured"]].map(([Icon, title, copy]) => { const I = Icon as typeof Factory; return <div key={title as string}><I /><span><strong>{title as string}</strong><small>{copy as string}</small></span></div>; })}</div></section>
    <section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Find your format</span><h2>Purpose-built for how you play.</h2><p className="lead">Choose by use, surface and age—not just by graphics.</p></div><Link className="text-link" href="/shop/">Explore all footballs <ArrowRight /></Link></div><div className="category-grid">{categories.map((item) => <Link className="category-card" href={item.href} key={item.category}><Image src={item.image} alt="" width={480} height={350} /><div><h3>{categoryLabels[item.category]}</h3><p>{item.copy}</p><span>Explore <ArrowRight /></span></div></Link>)}</div></div></section>
    <section className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">Starting line-up</span><h2>Football concepts worth exploring.</h2><p className="lead">Demonstration products show how the future verified catalogue can work.</p></div><Link className="button secondary" href="/shop/">View catalogue</Link></div><div className="product-grid">{products.filter((item) => item.featured).slice(0, 6).map((product) => <ProductCard product={product} key={product.id} />)}</div></div></section>
    <section className="section factory-story"><div className="container split-feature"><div className="feature-visual"><Image src="/images/factory-process.svg" alt="Illustrated football development process from panel to packed ball" width={760} height={640} /></div><div><span className="eyebrow">Made where footballs are made</span><h2>A direct line to Sialkot craftsmanship.</h2><p className="lead">Sialkot has a deep manufacturing culture built around skilled hands, material knowledge and specialist supply networks. Our role is to turn your intended use into a clear, workable football specification.</p><div className="story-steps"><span><b>01</b><strong>Define</strong><small>Use, surface, construction and quantity</small></span><span><b>02</b><strong>Develop</strong><small>Materials, artwork and sampling</small></span><span><b>03</b><strong>Deliver</strong><small>Inspect, pack and arrange shipping</small></span></div><Link className="button primary" href="/factory/">Explore the factory process <ArrowRight /></Link></div></div></section>
    <section className="section dark quality-section"><div className="container"><div className="section-head"><div><span className="eyebrow">A seven-step view</span><h2>Quality is a process, not a slogan.</h2></div><Link className="button hero-secondary" href="/quality/">Our quality approach</Link></div><div className="process-grid">{["Material selection", "Panel cutting", "Printing", "Stitching or bonding", "Shape inspection", "Air-retention checks", "Packing"].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item}</h3></div>)}</div><p className="process-disclaimer">Checks and acceptance criteria must be agreed for the actual product. Custom testing requirements can be discussed for wholesale orders.</p></div></section>
    <section className="section custom-block"><div className="container custom-panel"><div><span className="eyebrow">Make it recognizably yours</span><h2>From blank panels to your club, campaign or brand.</h2><p>Bring your logo, palette and purpose. We can discuss print placement, panel colors, presentation boxes, bulk packing and private-label details.</p><div className="icon-list">{[[Palette, "Logo & color"], [Layers3, "Construction"], [Boxes, "Packaging"], [Tags, "Private label"]].map(([Icon, label]) => { const I = Icon as typeof Palette; return <span key={label as string}><I />{label as string}</span>; })}</div><p className="fine-print">Minimum quantities vary by material, construction, artwork and packaging and must be confirmed.</p><Link href="/custom-footballs/" className="button gold">Start a custom project <ArrowRight /></Link></div><Image src="/images/custom-football-workbench.svg" alt="Custom football design workbench placeholder illustration" width={650} height={650} /></div></section>
    <section className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">Built for group buying</span><h2>One factory conversation. Many kinds of team.</h2></div><Link className="text-link" href="/wholesale/">Wholesale inquiries <ArrowRight /></Link></div><div className="buyer-grid">{[[Users, "Clubs", "Match, training and supporter concepts"], [GraduationCap, "Academies", "Size-mixed training inventories"], [School, "Schools", "Practical team and lesson supply"], [Store, "Retailers", "Original ranges and private labels"], [Sparkles, "Promotional", "Branded campaigns and events"]].map(([Icon, title, copy]) => { const I = Icon as typeof Users; return <div key={title as string}><I /><h3>{title as string}</h3><p>{copy as string}</p></div>; })}</div></div></section>
    <section className="section shipping-feature"><div className="container split-feature reverse"><div><span className="eyebrow">Sialkot to your doorstep</span><h2>International shipping, explained before you commit.</h2><p className="lead">Freight is shaped by carton size, quantity, destination and service level. We confirm the route, estimate and shipping basis during order processing—never hide it behind a fake calculator.</p><div className="shipping-points"><span><Truck /> Production and transit shown separately</span><span><Globe2 /> Destination-specific customs disclaimer</span><span><ShoppingBag /> USD base price retained in order summary</span></div><Link href="/shipping/" className="button primary">Read shipping guidance</Link></div><div className="world-card"><Globe2 /><strong>Worldwide</strong><span>USA · UK · Europe · Canada · International</span><small>No local inventory or warehouse is claimed unless explicitly configured.</small></div></div></section>
    <section className="section soft"><div className="container"><div className="section-head"><div><span className="eyebrow">Sample testimonials</span><h2>The space your real customer voices will earn.</h2><p>These layout samples are not verified purchases and must be replaced with authentic, permissioned reviews.</p></div></div><div className="testimonial-grid">{[["Sample club buyer", "The inquiry process helped us identify sizes and branding questions before requesting a final quote."], ["Sample academy coordinator", "A clear distinction between training and match specifications made planning the ball fleet easier."], ["Sample retailer", "The private-label checklist gave us a practical starting point for packaging and product development."]].map(([name, quote]) => <blockquote key={name}><span>Sample content</span><p>“{quote}”</p><cite>{name} · Not a verified review</cite></blockquote>)}</div></div></section>
    <section className="section"><div className="container faq-split"><div><span className="eyebrow">Good questions travel well</span><h2>Frequently asked.</h2><p className="lead">Clear answers now prevent expensive assumptions later.</p><Link className="text-link" href="/faq/">View all FAQs <ArrowRight /></Link></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
    <section className="section newsletter-section"><div className="container"><Newsletter /></div></section>
    <section className="final-cta"><div className="container"><span className="eyebrow">Your next football starts here</span><h2>Choose from the catalogue.<br />Or create what does not exist yet.</h2><div><Link className="button gold" href="/shop/">Shop footballs <ArrowRight /></Link><Link className="button hero-secondary" href="/wholesale/">Request a quote</Link></div></div></section>
    <JsonLd data={{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }} />
  </>;
}
