import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { InquiryForm } from "@/components/forms/inquiry-form";
import { PageHero } from "@/components/page-hero";
import { ProductCard } from "@/components/products/product-card";
import { products } from "@/data/products";
import { canonicalUrl } from "@/lib/commerce";
export const metadata: Metadata = { title: "Custom Footballs", description: "Plan custom logo footballs, colors, packaging and private-label specifications direct from Sialkot.", alternates: { canonical: canonicalUrl("/custom-footballs/") } };
export default function Page() { const custom = products.filter((item) => item.category === "custom"); return <><PageHero eyebrow="Your identity, developed on the ball" title="Custom footballs without the guesswork." description="A structured path for clubs, academies, schools, events, retailers and promotional teams to develop logo footballs from Sialkot." crumbs={[{ label: "Home", href: "/" }, { label: "Custom footballs" }]} /><section className="section"><div className="container"><div className="custom-steps"><div><span>01</span><h2>Brief</h2><p>Use, size, quantity, surface, construction and destination.</p></div><div><span>02</span><h2>Design</h2><p>Logo artwork, color references, print positions and packaging.</p></div><div><span>03</span><h2>Approve</h2><p>Review artwork and, when arranged, a physical sample.</p></div><div><span>04</span><h2>Produce</h2><p>Confirm schedule after the complete specification is accepted.</p></div></div><div className="prose custom-copy"><h2>What can be customized?</h2><p>Logo printing, panel colors, graphic layouts, construction, size, packaging and private-label presentation can be discussed. Practical options depend on quantity, material and print process.</p><ul>{["Vector artwork is preferred for clean logo reproduction.", "Color references should be supplied; material and print method affect the final result.", "Individual boxes, bulk packing and insert concepts can be reviewed.", "Minimum quantities are not invented here—they must be confirmed for the chosen specification.", "Custom testing requirements can be discussed for wholesale orders."].map((item) => <li key={item}><CheckCircle2 />{item}</li>)}</ul></div><div className="product-grid two-products">{custom.map((product) => <ProductCard product={product} key={product.id} />)}</div></div></section><section className="section soft"><div className="container form-section-grid"><div><span className="eyebrow">Start the right conversation</span><h2>Share the specification you know.</h2><p className="lead">Unknown details are fine. Quantity, destination and intended use give us a productive starting point.</p><Link className="text-link" href="/private-label/">Planning a retail brand? Explore private label →</Link></div><InquiryForm title="Request a custom football discussion" /></div></section></>; }
